version: '3.8'

services:
  percona-db:
    image: percona/percona-server:8.0
    container_name: percona-db
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
    command: --default-authentication-plugin=mysql_native_password --bind-address=0.0.0.0
    volumes:
      - percona_data:/var/lib/mysql

volumes:
  percona_data: